
- name: HANDLER EXAMPLE
  hosts: ubuntu
  become: yes
  gather_facts: no

  tasks:
    - name: Install Web Server
      package: 
        name: apache2
        state: present
      notify:
        - restart apache
  
  handlers: 
    - name: restart apache
      service: 
        name: apache2
        state: restarted